language: ruby
rvm:
- 2.3.0
notifications: email:false
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export JASMINE_SPEC_FORMAT=documentation
script:
- bundle exec rake db:create
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake db:test:prepare
- bundle exec rspec spec
- bundle exec rake jasmine:ci
- bundle exec cucumber
addons:
  code_climate:
    repo_token: "$CODECLIMATE_TOKEN"
deploy:
  provider: heroku
  api_key:
    secure: Zlgnqz+fVQ79RQFOg1+T6e/WR02MI97CIstUDARq75R2wgnsPM+Ssy9TtnL9LXs7dHAKqMEQvrWUNWQjGn7kNGUIsdR8lXqEpo5WPqKAY4XBJC6msfMewKa+tJZH/bLYbEg2LJWX/kTZ7kVl+oUHFnteBDLmE9TwxRKDbknz77UDwmS1ybfrr4gDoeWQvbRdXkZuL9imt2AyCjG+ENRjlmLT4K9bXqnTIT4RHyfX1rwiA1Z2QHjztNa47+nZXe4D+T6wnt/nEDovxqoMdmIVO4kyHBCvLz9n2Ie8SVt1mrBL+6hd9sadjzM8ELuNr800e83jpxQ4sIjX909Sxb8+ZHPkSrT4qWlhmxOUnSCjVLP2iLJQX5RxjMtmuCZvh44DPAeZnZBrVOgEomULrG+mnovq/VybrZeW84YGF+QkqQrcQ8GjCkiONmxZbGRFTCPcX1xU5cpeLeGXW0zUH6w7wr26PtL+eFfWUuI7MajfX1aejBqE4xbG8B5nCEctslBuW6uoH8hsRnFOXfbmCzOP52H/js8KYblzRskS84+t+3JVj8rjWhA5tr7KZDaMQE6ajr1NPP2/KQKC3P+IuVmzQdyxPoA96XHXF5Iqp408evFOdR+wLTsxb64BaL4rsF0K7QIVfuovR0oL4wv+yBn9N/JpTW1Ov65iCldinntBd/M=
  app: qt-community-stats
  on:
    repo: tintintti/qt-software-project
