language: ruby
rvm:
- 2.3.0
notifications: email:false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "export JASMINE_SPEC_FORMAT=documentation"
script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rspec spec"
  - "bundle exec rake jasmine:ci"
  - "bundle exec cucumber"
deploy:
  provider: heroku
  api_key:
    secure: Jrjk+KpoZvxKWrO1+wtDdJBxWR8zARVW3JTJXlFkXBuuGAxLyvZIw6MLnJc/0L6Le7K4GL7SsWPlczf2A0kMBDtv3lwAbrCAtFN4dMWZ2w/WLxoj5HcBvL9nBsJ2lIcPB7Z+RceJu2XjRDeF16fDMtFDFGR5pH+Tppb/s7eAk1dE1+R4v0SYCjkoiqAnBUl9/jNuGdZ3GMtBVLDVMolNZ4hfTG5DF9G3ZziAvop+Pq7uVfYMPBl9RT32IRdSfK66ydZoYJqE+48+lqLcIeA0MS9ucNBjiQWhfL3vXp0WO8IFiH7pXG7ZRbjPjOTLMIOwil8coMu3aSqh+qu83v88xpwfDnYjoo/Cv+DNH6W++AHUFpCnfseK5nCg8PzRPzFodr6olGu9AnPPLPrhuzkAkVUTq27Fy6ney2HYfAf8rA/lfArGjscOKTRB42UkK2dsXzd442RQT9zr3acUEFztzThTX7Cn+kTFPjskZpHVMpIwf19Xue0wLJyy7Sevi7XqItzojxgRN36Vp7Amxsas+UxHypPwsR0fKQ7wU7DHWAmH+r2VH2LsMKq34PuiVazbzITH9bkOaCObO13WpGq1+G6ciTo6ZqowfplNGxMVJhek5JTXmrP+pLCBJumn+LUHbSnO1bHy8X0v0EJ378nGB2luzgV6q3Qphm2Xo1rVzxQ=
  app: qt-software-project
  on:
    repo: tintintti/qt-software-project
addons:
  code_climate:
    repo_token: $CODECLIMATE_TOKEN
