language: ruby
rvm:
- 2.3.0
notifications: email:false
deploy:
  api_key:
    secure: Q1bwmxpY5ZmG++cK5xz1bvbqaQi8KUeh5VbfU1KruanWjW64/D9NqP/9BTzWR9hC/2Wns9vRKXeEKLuZ5udsbOHYvyzBvJnIbFFkLNgnQ2grlTNxg2DZb1oBQF5rlhhNa0M1OJJoBJlyTfOFmflyY1TbKvYCwQoSnckUMMkSIBfu9zdFc83Co0ynrKj4/EHJ8BDkMMPJOIq++CAvbSeyrHL6H8v8fRva1krKQY8nmsCUy8UVqWrkHugJYxK4asevWA58FzcT+OnEJQv1O+8zfiHoEFDh4gDA84RZV0FzjPaR5lt9HQs0HjIBOR3hEV/Zfjz5shKJZ6gqIbyFYjcS/4p7l4N/gsE0+gE43lTw9jndXEyNBJslyF87vtMjTjXF1nf619kMDZkcnIamCGrVn6ozbEyxfLSGoh1/TSls3WBkxAgUPE7PawKgHn9cAuwO66p0+6DzFLKydvqDZZNoAkQs2tkqchDMNTx1V50oxZqOP036BrTJE5z+lPRT62lwsBz8fDQzZfbpn4P4ulbCFxCgou9sn3dzxs3vZsIOM5dHo+vZDWxUHqAnoAxUV5U1AF/VivOlOPVz46tDuD2yOC+zx7MYxMGSeh002cAGRZNyiNus5f0h1Ftdu4+HRlMKT725wp1qF8u+Bq05rWDoX7F9nQjW9c4i2xI5+t6zUIU=
